version: '3.8'
services:
  backend:
    build: ./cvRankerBack
    ports: ["8080:8080"]
    restart: unless-stopped
    networks: ["cv-network"]

  frontend:
    build: ./cvRankerFront
    ports: ["4200:80"]
    depends_on: ["backend"]
    networks: ["cv-network"]

networks:
  cv-network:
    driver: bridge
