version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - cv-network

  backend:
    build: ./cvRankerBack
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - cv-network

  frontend:
    build: ./cvRankerFront
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - cv-network

networks:
  cv-network:
    driver: bridge

volumes:
  mongo-data:
