spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cvRanker  # Use the service name defined in docker-compose.yml

  application:
    name: cvRanker

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

