name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Backend ---
      - name: Build and push backend Docker image
        run: |
          docker build -t ghcr.io/devtaissirhammouda/cv-ranker-back:latest -f cvRankerBack/Dockerfile cvRankerBack
          docker push ghcr.io/devtaissirhammouda/cv-ranker-back:latest

      # --- Frontend ---
      - name: Build and push frontend Docker image
        run: |
          docker build -t ghcr.io/devtaissirhammouda/cv-ranker-front:latest -f cvRankerFront/Dockerfile cvRankerFront
          docker push ghcr.io/devtaissirhammouda/cv-ranker-front:latest
