name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: cvRankerFront
        run: npm install

      - name: Build Angular frontend
        working-directory: cvRankerFront
        run: npm run build --prod

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot backend
        working-directory: cvRankerBack
        run: ./mvnw clean package -DskipTests
